language: r
r: bioc-release
pandoc_version: 1.17.2
apt_packages: libnetcdf-dev
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
r_github_packages:
- dgrtwo/ebbr
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: uyr1E2iFglePUAWmG3qXmJM0FzX27/btv0VCwb9Uv9uFN4m51PNMACADX0d4I/ZktCPcrc2qKRwyZ15R4mZX/iQWSJeUaLzVB54inFzypmQCe9maFs565TBOip6reGeRoyyQ01/BsnH4cPJgRX6/W+yvGt/P5iAfUGE8wi3UD2K2jPtCFE/mbpgXlHSondHh2fCHB4OzrWI4tFOc7aFanXbGBKs3BQHr3Ma2xdV1kQd/63RCw61JD3tvqsdi+Bh6u6yL0Yyuf9DRzl65DK1hUFY6DQnjuyrvBLEqA9jXQhVUMhbJMwbCjpd/Ica0RtRHzVIO6Yl/FK0PeGq6fN4JJkRUujmKmeeiUuBRW0ZiwehBVWB4r5Or1gQ5ci9qPplptvSaL+8Bk1HWzpi4KQxefDfCKLvzabSqC198vgWZ5ORbD0geyDJmibRqDg2/2mGEWFgJG75rRXiFONkmFhn+8uvD4i7H56oxrCZJt4krfhaDDJt+XoN5Y2EvFBFLAK/XVYmZ7Dghod0Mvw6a79X1kI1ub0AeNT+kPE3eOWNt+bcn96Z9TSKWitBcFLdvyYDTCISxvo5pnhR3kiY5hHRg49TnJzMUEVMerxn1BqEbgWao8+Veo2oLeHa+FFjPTdrvwswC12LYVUEaKpDgXvmOLwVoYi76vk4Bsz8yNd0c6mk=
