language: r
r: bioc-release
pandoc_version: 1.17.2
apt_packages: libnetcdf-dev
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
r_github_packages:
  - dgrtwo/ebbr
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
env:
  global:
  - secure: zHTTW4R4xIwkkfPN+b+31iIJdGlC96GKKlr7GHx3hcxRsmtgfTv4piqeh/hG/XzyOUkBIb9tyBOONLtFLIxxYZcI93n7nlavZcVOz3uo+Mj+MMh8AUxqopfaxXrNf4GvYeLtZnkouUdm4fUOnMSuWWCh1ex0UkFSWqwKVzgB/NeokdupR+KqJDj8gMB76AMIFxYmr+Bl1OlIDNMQhEPJcO5GY7wGHE4PeIHpWKkRHHakxgXOhuaxFaFpVqtfrwHnDQyzyTB1HlMRJnuVaBGhbZ3POCIBP2ocMrwhSbpNES9SrpsNZnYpfCBy9CYxTjhpUQ+cDljriwGV4nNrEQdKgXUhsiWnK3TLsl8RN1reiwlyOJEwPAECa1nWnUeZPaFq+GDcr0Mfd/7LcuEm5FI4s0/88su27izGzqKQ9iqbkqebgd35Lg8wFoYnERqy8W37zbAkGwdoHTzaUdd1RaFNfVEOrmC+idDlZhoL1LWCnRsTxJIxDF8lDupGNvyd/YC5OoZ2ijK8TtBskKeAb4pw6LDNMApPqITo3YbK9vvcUXs4d6/rr7RjmUEvzdydTedEWAsHznUaIui43ZfPxEVRoA45n1A7/9tFm6X8OVP8tP+nzXji4uE7zrj3WPrkQmtQ6auyJk0hFPsYjN5hkQGGZ10h7Yugzx3cVeYyVp3FX+w=
