language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
apt_packages: libnetcdf-dev
env:
  global:
  - secure: UkOLlO8/NzWN2tJEKFbV6Pb2vYRkaEYWxSg50P5NU8AlmiYiRnkyL1a8GotwTt7gM5pZKe14XahVR1oEqvpQUcAOdAIroeCbV4Ri9gPZXgNdJeivi2fafG08+OYCpzqiCTFnLwUrpN8SOr6WNXjmfEufv7Hh+Bkxez7xBu7RnWu8k/Eo34LZ85DqsE48L9jLIph5HJ0pZrqNOwIvfrH3JLCHLk0gBg3Civl6FKC+V1Kz8QtPxmEfscRg1NP1lmad3moEI6r4Pp+lgwMmXy+7TGlpLC2KANoWAXE/QLt69+lVOjzq/A/wQSuJX5ftJxfvhqzEB2qMn+CVqVGdhv1TUSg9KTK3qzxa+V0q31iz0BSXp0bGpGxMte6CQFTdmovMmEbVIaGLo7a9afAy2MAreQG9usxEnfuJ2VNzOr22iFZ3cdlrweEI73n3n5nAL4HyBuCyfSNEXIVWX07xLmlMEk16Xe+tjkm1E590cKtNe/PnZHOwGxtVHW5QYpTD9yttNFTTbrdWqiIs2ZWXbLwHRkxVurywhPY+MvIbgsWcGJaEfvcjyApcZKOKan7M+3yVAJpAxl9M9mk7+a98gD4xu1h2tJv4relvUd5mRJmB2oqJ17eHWuNtD8OrmCzFuHC110Jkh17+l2hk5XdF61RbTnYY8qwQIZWRL/E82rz4sXk=
